-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 12-12-2023 a las 04:56:42
-- Versión del servidor: 10.4.27-MariaDB
-- Versión de PHP: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `audifonos`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `carrito`
--

CREATE TABLE `carrito` (
  `id` int(10) NOT NULL,
  `nombre` varchar(70) NOT NULL,
  `descripcion` varchar(1900) NOT NULL,
  `precioSD` int(10) NOT NULL,
  `precioF` int(10) NOT NULL,
  `imagen` varchar(600) NOT NULL,
  `usuario` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `carrito`
--

INSERT INTO `carrito` (`id`, `nombre`, `descripcion`, `precioSD`, `precioF`, `imagen`, `usuario`) VALUES
(2, 'JBL Auriculares In-Ear', 'Los auriculares JBL In-Ear ofrecen una experiencia auditiva envolvente en un diseño compacto y cómodo. Diseñados para ajustarse perfectamente en el canal auditivo, estos auriculares in-ear proporcionan un sonido claro y nítido con un énfasis en los bajos, que es característico de la calidad de audio que se espera de la marca JBL. Con su construcción ergonómica, ofrecen comodidad durante periodos prolongados de uso y son ideales para actividades en movimiento. Algunos modelos pueden incluir características adicionales, como controles integrados para gestionar la reproducción de música y llamadas, así como micrófonos incorporados para una comunicación manos libres.', 1349, 1349, 'uploads/JBL - Auriculares In-Ear True Wireless Vibe 200TWS.jpg', ''),
(3, 'Sony WF-C500', 'Los auriculares inalámbricos Sony WF-C500 ofrecen una experiencia auditiva compacta y conveniente en un diseño ergonómico y sin cables. Diseñados para proporcionar un ajuste seguro y cómodo en el oído, estos auriculares son ideales para aquellos que buscan movilidad y libertad durante sus actividades diarias. Con tecnología Bluetooth, los Sony WF-C500 se conectan fácilmente a dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esta conectividad inalámbrica permite una experiencia sin enredos y sin restricciones, lo que facilita el uso en movimiento. Estos auriculares ofrecen una calidad de sonido equilibrada, con énfasis en los detalles y una reproducción clara de las frecuencias. Además, cuentan con controles táctiles intuitivos en cada auricular, lo que facilita la gestión de la reproducción de música, la respuesta a llamadas y la navegación entre pistas de manera sencilla.', 2499, 2200, 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.jpg', ''),
(5, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', ''),
(6, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', ''),
(7, 'Sony WF-C500', 'Los auriculares inalámbricos Sony WF-C500 ofrecen una experiencia auditiva compacta y conveniente en un diseño ergonómico y sin cables. Diseñados para proporcionar un ajuste seguro y cómodo en el oído, estos auriculares son ideales para aquellos que buscan movilidad y libertad durante sus actividades diarias. Con tecnología Bluetooth, los Sony WF-C500 se conectan fácilmente a dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esta conectividad inalámbrica permite una experiencia sin enredos y sin restricciones, lo que facilita el uso en movimiento. Estos auriculares ofrecen una calidad de sonido equilibrada, con énfasis en los detalles y una reproducción clara de las frecuencias. Además, cuentan con controles táctiles intuitivos en cada auricular, lo que facilita la gestión de la reproducción de música, la respuesta a llamadas y la navegación entre pistas de manera sencilla.', 2499, 2200, 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.jpg', ''),
(8, 'Sony WF-C500', 'Los auriculares inalámbricos Sony WF-C500 ofrecen una experiencia auditiva compacta y conveniente en un diseño ergonómico y sin cables. Diseñados para proporcionar un ajuste seguro y cómodo en el oído, estos auriculares son ideales para aquellos que buscan movilidad y libertad durante sus actividades diarias. Con tecnología Bluetooth, los Sony WF-C500 se conectan fácilmente a dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esta conectividad inalámbrica permite una experiencia sin enredos y sin restricciones, lo que facilita el uso en movimiento. Estos auriculares ofrecen una calidad de sonido equilibrada, con énfasis en los detalles y una reproducción clara de las frecuencias. Además, cuentan con controles táctiles intuitivos en cada auricular, lo que facilita la gestión de la reproducción de música, la respuesta a llamadas y la navegación entre pistas de manera sencilla.', 2499, 2200, 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.jpg', ''),
(10, 'JBL Auriculares In-Ear', 'Los auriculares JBL In-Ear ofrecen una experiencia auditiva envolvente en un diseño compacto y cómodo. Diseñados para ajustarse perfectamente en el canal auditivo, estos auriculares in-ear proporcionan un sonido claro y nítido con un énfasis en los bajos, que es característico de la calidad de audio que se espera de la marca JBL. Con su construcción ergonómica, ofrecen comodidad durante periodos prolongados de uso y son ideales para actividades en movimiento. Algunos modelos pueden incluir características adicionales, como controles integrados para gestionar la reproducción de música y llamadas, así como micrófonos incorporados para una comunicación manos libres.', 1349, 1349, 'uploads/JBL - Auriculares In-Ear True Wireless Vibe 200TWS.jpg', ''),
(12, 'Huawei Freebuds 5i', 'Los Huawei FreeBuds 5i son auriculares inalámbricos que ofrecen una experiencia auditiva cómoda y conveniente. Diseñados por Huawei, estos auriculares proporcionan una conectividad sin cables para una experiencia de escucha inalámbrica. Estos auriculares cuentan con un diseño ergonómico que se adapta cómodamente al oído, proporcionando un ajuste seguro y cómodo durante períodos prolongados de uso. Además, su diseño compacto y liviano facilita su transporte y almacenamiento, convirtiéndolos en una opción práctica para el uso diario. La conectividad Bluetooth permite emparejar fácilmente los FreeBuds 4i con dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esto ofrece la libertad de moverse sin restricciones, ya que no hay cables que limiten la movilidad del usuario.', 1199, 1199, 'uploads/Huawei FreeBuds 5i.png', ''),
(13, 'Apple Airpods Pro', 'Los Apple AirPods Pro son auriculares inalámbricos de última generación que ofrecen una experiencia auditiva excepcional. Destacan por su tecnología de Cancelación Activa de Ruido (ANC), sumergiendo al usuario en un sonido envolvente al filtrar eficazmente los sonidos externos. Además, cuentan con el innovador Modo de Transparencia, permitiendo la entrada de sonidos ambientales cuando sea necesario. Su diseño intrauditivo proporciona un ajuste cómodo y personalizado, respaldado por diferentes tamaños de almohadillas. Estos auriculares incluyen características avanzadas, como audio espacial para una experiencia tridimensional, controles táctiles intuitivos, resistencia al agua y al sudor con certificación IPX4, y sensores que pausan la reproducción automáticamente al retirarlos. ', 5499, 5499, 'uploads/Apple AirPods Pro (Segunda generación).jpg', ''),
(14, 'HTC', 'Los audífonos HTC Inalámbricos con tecnología Bluetooth 5.3 representan una opción avanzada para disfrutar de una experiencia auditiva sin cables. Estos auriculares, diseñados en el formato de \"earbuds\" inalámbricos, garantizan una conectividad rápida y estable gracias a la versión 5.3 de Bluetooth. Su posible inclusión de cancelación de ruido contribuye a aislar al usuario de distracciones externas, mientras que los controles táctiles o físicos permiten gestionar funciones como cambiar de pista o ajustar el volumen con facilidad. Con un estuche de carga que no solo protege sino que también proporciona cargas adicionales, estos audífonos se destacan por su diseño ergonómico, ofreciendo comodidad durante sesiones auditivas prolongadas.', 4999, 4899, 'uploads/HTC Audifonos.jpg', ''),
(15, 'HTC', 'Los audífonos HTC Inalámbricos con tecnología Bluetooth 5.3 representan una opción avanzada para disfrutar de una experiencia auditiva sin cables. Estos auriculares, diseñados en el formato de \"earbuds\" inalámbricos, garantizan una conectividad rápida y estable gracias a la versión 5.3 de Bluetooth. Su posible inclusión de cancelación de ruido contribuye a aislar al usuario de distracciones externas, mientras que los controles táctiles o físicos permiten gestionar funciones como cambiar de pista o ajustar el volumen con facilidad. Con un estuche de carga que no solo protege sino que también proporciona cargas adicionales, estos audífonos se destacan por su diseño ergonómico, ofreciendo comodidad durante sesiones auditivas prolongadas.', 4999, 4899, 'uploads/HTC Audifonos.jpg', ''),
(16, 'HTC', 'Los audífonos HTC Inalámbricos con tecnología Bluetooth 5.3 representan una opción avanzada para disfrutar de una experiencia auditiva sin cables. Estos auriculares, diseñados en el formato de \"earbuds\" inalámbricos, garantizan una conectividad rápida y estable gracias a la versión 5.3 de Bluetooth. Su posible inclusión de cancelación de ruido contribuye a aislar al usuario de distracciones externas, mientras que los controles táctiles o físicos permiten gestionar funciones como cambiar de pista o ajustar el volumen con facilidad. Con un estuche de carga que no solo protege sino que también proporciona cargas adicionales, estos audífonos se destacan por su diseño ergonómico, ofreciendo comodidad durante sesiones auditivas prolongadas.', 4999, 4899, 'uploads/HTC Audifonos.jpg', ''),
(17, 'HTC', 'Los audífonos HTC Inalámbricos con tecnología Bluetooth 5.3 representan una opción avanzada para disfrutar de una experiencia auditiva sin cables. Estos auriculares, diseñados en el formato de \"earbuds\" inalámbricos, garantizan una conectividad rápida y estable gracias a la versión 5.3 de Bluetooth. Su posible inclusión de cancelación de ruido contribuye a aislar al usuario de distracciones externas, mientras que los controles táctiles o físicos permiten gestionar funciones como cambiar de pista o ajustar el volumen con facilidad. Con un estuche de carga que no solo protege sino que también proporciona cargas adicionales, estos audífonos se destacan por su diseño ergonómico, ofreciendo comodidad durante sesiones auditivas prolongadas.', 4999, 4899, 'uploads/HTC Audifonos.jpg', ''),
(18, 'Bose Noise', 'Los auriculares Bose Noise Cancelling Headphones ofrecen una experiencia auditiva excepcional gracias a su tecnología de cancelación de ruido líder en la industria. Diseñados para sumergir al usuario en un mundo de sonido de alta calidad, estos auriculares cuentan con características avanzadas para una experiencia premium. La cancelación de ruido adaptativa ajusta continuamente la intensidad de la cancelación de acuerdo con el entorno, brindando una inmersión total en la música, podcasts o llamadas. Con un diseño elegante y cómodo, los Bose Noise Cancelling Headphones son ideales para un uso prolongado. Los controles táctiles intuitivos permiten un manejo sencillo, mientras que la duración de la batería garantiza largas horas de disfrute sin interrupciones.', 10099, 10099, 'uploads/Bose Noise Cancelling Headphones 700.jpg', ''),
(19, 'Bose Noise', 'Los auriculares Bose Noise Cancelling Headphones ofrecen una experiencia auditiva excepcional gracias a su tecnología de cancelación de ruido líder en la industria. Diseñados para sumergir al usuario en un mundo de sonido de alta calidad, estos auriculares cuentan con características avanzadas para una experiencia premium. La cancelación de ruido adaptativa ajusta continuamente la intensidad de la cancelación de acuerdo con el entorno, brindando una inmersión total en la música, podcasts o llamadas. Con un diseño elegante y cómodo, los Bose Noise Cancelling Headphones son ideales para un uso prolongado. Los controles táctiles intuitivos permiten un manejo sencillo, mientras que la duración de la batería garantiza largas horas de disfrute sin interrupciones.', 10099, 10099, 'uploads/Bose Noise Cancelling Headphones 700.jpg', ''),
(22, 'Sennheiser Cx', 'Calidad de Sonido: Sennheiser es conocido por ofrecer una calidad de sonido de alta fidelidad. Los auriculares CX suelen proporcionar una reproducción precisa de graves, medios y agudos, brindando una experiencia auditiva equilibrada. Diseño Intrauditivo: Los auriculares CX son del tipo intrauditivo, lo que significa que se colocan directamente en el canal auditivo. Este diseño ayuda a aislar el sonido ambiental y mejora la calidad del audio al proporcionar un sellado más efectivo. Conectividad: Dependiendo del modelo, algunos auriculares CX pueden ser con cable (con conector de 3.5 mm) o inalámbricos, utilizando tecnologías como Bluetooth.', 399, 399, 'uploads/Sennheiser Audífonos CX 80S.jpg', ''),
(23, 'Sennheiser Cx', 'Calidad de Sonido: Sennheiser es conocido por ofrecer una calidad de sonido de alta fidelidad. Los auriculares CX suelen proporcionar una reproducción precisa de graves, medios y agudos, brindando una experiencia auditiva equilibrada. Diseño Intrauditivo: Los auriculares CX son del tipo intrauditivo, lo que significa que se colocan directamente en el canal auditivo. Este diseño ayuda a aislar el sonido ambiental y mejora la calidad del audio al proporcionar un sellado más efectivo. Conectividad: Dependiendo del modelo, algunos auriculares CX pueden ser con cable (con conector de 3.5 mm) o inalámbricos, utilizando tecnologías como Bluetooth.', 399, 399, 'uploads/Sennheiser Audífonos CX 80S.jpg', ''),
(24, 'Sennheiser Cx', 'Calidad de Sonido: Sennheiser es conocido por ofrecer una calidad de sonido de alta fidelidad. Los auriculares CX suelen proporcionar una reproducción precisa de graves, medios y agudos, brindando una experiencia auditiva equilibrada. Diseño Intrauditivo: Los auriculares CX son del tipo intrauditivo, lo que significa que se colocan directamente en el canal auditivo. Este diseño ayuda a aislar el sonido ambiental y mejora la calidad del audio al proporcionar un sellado más efectivo. Conectividad: Dependiendo del modelo, algunos auriculares CX pueden ser con cable (con conector de 3.5 mm) o inalámbricos, utilizando tecnologías como Bluetooth.', 399, 399, 'uploads/Sennheiser Audífonos CX 80S.jpg', ''),
(25, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', ''),
(28, 'Sony WH1000XM4', 'Los auriculares Sony WH-1000XM4 son una obra maestra de la tecnología auditiva que combina un diseño elegante con un rendimiento excepcional. Reconocidos por su capacidad de cancelación de ruido líder en la industria, estos auriculares proporcionan una experiencia auditiva inmersiva al bloquear eficazmente los sonidos no deseados del entorno. Equipados con la tecnología de cancelación de ruido adaptativa, los WH-1000XM4 ajustan automáticamente la intensidad de la cancelación de ruido según el entorno, brindando una experiencia personalizada. La calidad de sonido es impresionante, con graves profundos y agudos claros que capturan cada detalle de la música.', 1899, 1899, 'uploads/Sony WH1000XM4-L Audífonos de Diadema inalámbricos con Noise Cancelling-Azul.jpg', ''),
(29, 'Sony WF-C500', 'Los auriculares inalámbricos Sony WF-C500 ofrecen una experiencia auditiva compacta y conveniente en un diseño ergonómico y sin cables. Diseñados para proporcionar un ajuste seguro y cómodo en el oído, estos auriculares son ideales para aquellos que buscan movilidad y libertad durante sus actividades diarias. Con tecnología Bluetooth, los Sony WF-C500 se conectan fácilmente a dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esta conectividad inalámbrica permite una experiencia sin enredos y sin restricciones, lo que facilita el uso en movimiento. Estos auriculares ofrecen una calidad de sonido equilibrada, con énfasis en los detalles y una reproducción clara de las frecuencias. Además, cuentan con controles táctiles intuitivos en cada auricular, lo que facilita la gestión de la reproducción de música, la respuesta a llamadas y la navegación entre pistas de manera sencilla.', 2499, 2200, 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.jpg', ''),
(30, 'Sony WF-C500', 'Los auriculares inalámbricos Sony WF-C500 ofrecen una experiencia auditiva compacta y conveniente en un diseño ergonómico y sin cables. Diseñados para proporcionar un ajuste seguro y cómodo en el oído, estos auriculares son ideales para aquellos que buscan movilidad y libertad durante sus actividades diarias. Con tecnología Bluetooth, los Sony WF-C500 se conectan fácilmente a dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esta conectividad inalámbrica permite una experiencia sin enredos y sin restricciones, lo que facilita el uso en movimiento. Estos auriculares ofrecen una calidad de sonido equilibrada, con énfasis en los detalles y una reproducción clara de las frecuencias. Además, cuentan con controles táctiles intuitivos en cada auricular, lo que facilita la gestión de la reproducción de música, la respuesta a llamadas y la navegación entre pistas de manera sencilla.', 2499, 2200, 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.jpg', ''),
(31, 'LINK BITS', '10 horas y carga USB: El auricular inteligente con cancelación de ruido puede proporcionar hasta 10 horas de tiempo de reproducción de música. Además, puede cargar estos auriculares inalámbricos a través del conveniente puerto tipo C, 5 minutos de carga son suficientes para obtener 1 horas de reproducción cuando la batería está baja. BLUETOOTH 5.0 y fácil de cambiar: Bluetooth 5.0 significa una transmisión más rápida y estable, menor consumo de energía y señales más estables. Puede admitir dos dispositivos Bluetooth al mismo tiempo. Por lo tanto, si estás viendo una película en tu iPad y entra una llamada a tu iPhone, los audífonos pausan el video y responden la llamada. Al finalizar la llamada, se reanuda la película. Diseño plegable&Cojín transpirable: diseño liviano, solo 209 g, la audifonos diadema se puede ajustable según el tama para mucho comodo. Además, las orejeras de proteína blanda con relleno de espuma viscoelástica se adaptan a sus oídos. Son muy adecuados para la oficina en casa, cursos online, viajes, música y televisión, etc.', 1200, 901, 'uploads/LINK BITS.jpg', ''),
(32, 'Sony WH1000XM4', 'Los auriculares Sony WH-1000XM4 son una obra maestra de la tecnología auditiva que combina un diseño elegante con un rendimiento excepcional. Reconocidos por su capacidad de cancelación de ruido líder en la industria, estos auriculares proporcionan una experiencia auditiva inmersiva al bloquear eficazmente los sonidos no deseados del entorno. Equipados con la tecnología de cancelación de ruido adaptativa, los WH-1000XM4 ajustan automáticamente la intensidad de la cancelación de ruido según el entorno, brindando una experiencia personalizada. La calidad de sonido es impresionante, con graves profundos y agudos claros que capturan cada detalle de la música.', 1899, 1899, 'uploads/Sony WH1000XM4-L Audífonos de Diadema inalámbricos con Noise Cancelling-Azul.jpg', ''),
(33, 'Sony WH1000XM4', 'Los auriculares Sony WH-1000XM4 son una obra maestra de la tecnología auditiva que combina un diseño elegante con un rendimiento excepcional. Reconocidos por su capacidad de cancelación de ruido líder en la industria, estos auriculares proporcionan una experiencia auditiva inmersiva al bloquear eficazmente los sonidos no deseados del entorno. Equipados con la tecnología de cancelación de ruido adaptativa, los WH-1000XM4 ajustan automáticamente la intensidad de la cancelación de ruido según el entorno, brindando una experiencia personalizada. La calidad de sonido es impresionante, con graves profundos y agudos claros que capturan cada detalle de la música.', 1899, 1899, 'uploads/Sony WH1000XM4-L Audífonos de Diadema inalámbricos con Noise Cancelling-Azul.jpg', ''),
(34, 'Huawei Freebuds 5i', 'Los Huawei FreeBuds 5i son auriculares inalámbricos que ofrecen una experiencia auditiva cómoda y conveniente. Diseñados por Huawei, estos auriculares proporcionan una conectividad sin cables para una experiencia de escucha inalámbrica. Estos auriculares cuentan con un diseño ergonómico que se adapta cómodamente al oído, proporcionando un ajuste seguro y cómodo durante períodos prolongados de uso. Además, su diseño compacto y liviano facilita su transporte y almacenamiento, convirtiéndolos en una opción práctica para el uso diario. La conectividad Bluetooth permite emparejar fácilmente los FreeBuds 4i con dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esto ofrece la libertad de moverse sin restricciones, ya que no hay cables que limiten la movilidad del usuario.', 1199, 1199, 'uploads/Huawei FreeBuds 5i.png', ''),
(35, 'Huawei Freebuds 5i', 'Los Huawei FreeBuds 5i son auriculares inalámbricos que ofrecen una experiencia auditiva cómoda y conveniente. Diseñados por Huawei, estos auriculares proporcionan una conectividad sin cables para una experiencia de escucha inalámbrica. Estos auriculares cuentan con un diseño ergonómico que se adapta cómodamente al oído, proporcionando un ajuste seguro y cómodo durante períodos prolongados de uso. Además, su diseño compacto y liviano facilita su transporte y almacenamiento, convirtiéndolos en una opción práctica para el uso diario. La conectividad Bluetooth permite emparejar fácilmente los FreeBuds 4i con dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esto ofrece la libertad de moverse sin restricciones, ya que no hay cables que limiten la movilidad del usuario.', 1199, 1199, 'uploads/Huawei FreeBuds 5i.png', ''),
(36, 'Huawei Freebuds 5i', 'Los Huawei FreeBuds 5i son auriculares inalámbricos que ofrecen una experiencia auditiva cómoda y conveniente. Diseñados por Huawei, estos auriculares proporcionan una conectividad sin cables para una experiencia de escucha inalámbrica. Estos auriculares cuentan con un diseño ergonómico que se adapta cómodamente al oído, proporcionando un ajuste seguro y cómodo durante períodos prolongados de uso. Además, su diseño compacto y liviano facilita su transporte y almacenamiento, convirtiéndolos en una opción práctica para el uso diario. La conectividad Bluetooth permite emparejar fácilmente los FreeBuds 4i con dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esto ofrece la libertad de moverse sin restricciones, ya que no hay cables que limiten la movilidad del usuario.', 1199, 1199, 'uploads/Huawei FreeBuds 5i.png', ''),
(37, 'LINK BITS', '10 horas y carga USB: El auricular inteligente con cancelación de ruido puede proporcionar hasta 10 horas de tiempo de reproducción de música. Además, puede cargar estos auriculares inalámbricos a través del conveniente puerto tipo C, 5 minutos de carga son suficientes para obtener 1 horas de reproducción cuando la batería está baja. BLUETOOTH 5.0 y fácil de cambiar: Bluetooth 5.0 significa una transmisión más rápida y estable, menor consumo de energía y señales más estables. Puede admitir dos dispositivos Bluetooth al mismo tiempo. Por lo tanto, si estás viendo una película en tu iPad y entra una llamada a tu iPhone, los audífonos pausan el video y responden la llamada. Al finalizar la llamada, se reanuda la película. Diseño plegable&Cojín transpirable: diseño liviano, solo 209 g, la audifonos diadema se puede ajustable según el tama para mucho comodo. Además, las orejeras de proteína blanda con relleno de espuma viscoelástica se adaptan a sus oídos. Son muy adecuados para la oficina en casa, cursos online, viajes, música y televisión, etc.', 1200, 901, 'uploads/LINK BITS.jpg', ''),
(38, 'LINK BITS', '10 horas y carga USB: El auricular inteligente con cancelación de ruido puede proporcionar hasta 10 horas de tiempo de reproducción de música. Además, puede cargar estos auriculares inalámbricos a través del conveniente puerto tipo C, 5 minutos de carga son suficientes para obtener 1 horas de reproducción cuando la batería está baja. BLUETOOTH 5.0 y fácil de cambiar: Bluetooth 5.0 significa una transmisión más rápida y estable, menor consumo de energía y señales más estables. Puede admitir dos dispositivos Bluetooth al mismo tiempo. Por lo tanto, si estás viendo una película en tu iPad y entra una llamada a tu iPhone, los audífonos pausan el video y responden la llamada. Al finalizar la llamada, se reanuda la película. Diseño plegable&Cojín transpirable: diseño liviano, solo 209 g, la audifonos diadema se puede ajustable según el tama para mucho comodo. Además, las orejeras de proteína blanda con relleno de espuma viscoelástica se adaptan a sus oídos. Son muy adecuados para la oficina en casa, cursos online, viajes, música y televisión, etc.', 1200, 901, 'uploads/LINK BITS.jpg', ''),
(40, 'Apple Airpods Pro', 'Los Apple AirPods Pro son auriculares inalámbricos de última generación que ofrecen una experiencia auditiva excepcional. Destacan por su tecnología de Cancelación Activa de Ruido (ANC), sumergiendo al usuario en un sonido envolvente al filtrar eficazmente los sonidos externos. Además, cuentan con el innovador Modo de Transparencia, permitiendo la entrada de sonidos ambientales cuando sea necesario. Su diseño intrauditivo proporciona un ajuste cómodo y personalizado, respaldado por diferentes tamaños de almohadillas. Estos auriculares incluyen características avanzadas, como audio espacial para una experiencia tridimensional, controles táctiles intuitivos, resistencia al agua y al sudor con certificación IPX4, y sensores que pausan la reproducción automáticamente al retirarlos. ', 5499, 5499, 'uploads/Apple AirPods Pro (Segunda generación).jpg', ''),
(49, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp'),
(50, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp'),
(51, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp'),
(52, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp'),
(53, 'Sony WF-C500', 'Los auriculares inalámbricos Sony WF-C500 ofrecen una experiencia auditiva compacta y conveniente en un diseño ergonómico y sin cables. Diseñados para proporcionar un ajuste seguro y cómodo en el oído, estos auriculares son ideales para aquellos que buscan movilidad y libertad durante sus actividades diarias. Con tecnología Bluetooth, los Sony WF-C500 se conectan fácilmente a dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esta conectividad inalámbrica permite una experiencia sin enredos y sin restricciones, lo que facilita el uso en movimiento. Estos auriculares ofrecen una calidad de sonido equilibrada, con énfasis en los detalles y una reproducción clara de las frecuencias. Además, cuentan con controles táctiles intuitivos en cada auricular, lo que facilita la gestión de la reproducción de música, la respuesta a llamadas y la navegación entre pistas de manera sencilla.', 2499, 2200, 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp'),
(56, 'Bose QuietComfort', 'La característica más destacada de estos auriculares es su capacidad para reducir significativamente el ruido ambiental. Esto es especialmente útil en entornos ruidosos, como aviones o espacios públicos, permitiendo a los usuarios sumergirse completamente en su música o contenido. Diseño cómodo: Los auriculares Bose suelen tener un diseño ergonómico y acolchado para ofrecer comodidad durante períodos de uso prolongado. Los materiales de alta calidad también contribuyen a la sensación premium. Calidad de sonido: Bose es conocido por proporcionar una calidad de sonido nítida y equilibrada', 13999, 13999, 'uploads/Bose QuietComfort Ultra con Audio Espacial.jpg', ''),
(57, 'Bose QuietComfort', 'La característica más destacada de estos auriculares es su capacidad para reducir significativamente el ruido ambiental. Esto es especialmente útil en entornos ruidosos, como aviones o espacios públicos, permitiendo a los usuarios sumergirse completamente en su música o contenido. Diseño cómodo: Los auriculares Bose suelen tener un diseño ergonómico y acolchado para ofrecer comodidad durante períodos de uso prolongado. Los materiales de alta calidad también contribuyen a la sensación premium. Calidad de sonido: Bose es conocido por proporcionar una calidad de sonido nítida y equilibrada', 13999, 13999, 'uploads/Bose QuietComfort Ultra con Audio Espacial.jpg', ''),
(61, 'Galaxy Buds 2 Pro', 'Los Samsung Galaxy Buds Pro 2 son auriculares inalámbricos que ofrecen una experiencia auditiva de alta calidad en un diseño compacto y ergonómico. Diseñados para adaptarse cómodamente al oído, estos auriculares son ligeros y vienen con almohadillas intercambiables para un ajuste personalizado. Destacan por proporcionar un sonido equilibrado con bajos profundos y agudos claros, brindando una experiencia auditiva inmersiva. Gracias a la conectividad Bluetooth, los Galaxy Buds se emparejan de manera rápida y sencilla con dispositivos compatibles, como teléfonos inteligentes y tabletas. Además, cuentan con controles táctiles intuitivos que permiten gestionar la reproducción de musica', 2699, 2699, 'uploads/SAMSUNG Galaxy Buds 2 Pro.jpg', 'cr7'),
(62, 'Galaxy Buds 2 Pro', 'Los Samsung Galaxy Buds Pro 2 son auriculares inalámbricos que ofrecen una experiencia auditiva de alta calidad en un diseño compacto y ergonómico. Diseñados para adaptarse cómodamente al oído, estos auriculares son ligeros y vienen con almohadillas intercambiables para un ajuste personalizado. Destacan por proporcionar un sonido equilibrado con bajos profundos y agudos claros, brindando una experiencia auditiva inmersiva. Gracias a la conectividad Bluetooth, los Galaxy Buds se emparejan de manera rápida y sencilla con dispositivos compatibles, como teléfonos inteligentes y tabletas. Además, cuentan con controles táctiles intuitivos que permiten gestionar la reproducción de musica', 2699, 2699, 'uploads/SAMSUNG Galaxy Buds 2 Pro.jpg', 'cr7'),
(63, 'Galaxy Buds 2 Pro', 'Los Samsung Galaxy Buds Pro 2 son auriculares inalámbricos que ofrecen una experiencia auditiva de alta calidad en un diseño compacto y ergonómico. Diseñados para adaptarse cómodamente al oído, estos auriculares son ligeros y vienen con almohadillas intercambiables para un ajuste personalizado. Destacan por proporcionar un sonido equilibrado con bajos profundos y agudos claros, brindando una experiencia auditiva inmersiva. Gracias a la conectividad Bluetooth, los Galaxy Buds se emparejan de manera rápida y sencilla con dispositivos compatibles, como teléfonos inteligentes y tabletas. Además, cuentan con controles táctiles intuitivos que permiten gestionar la reproducción de musica', 2699, 2699, 'uploads/SAMSUNG Galaxy Buds 2 Pro.jpg', 'cr7'),
(73, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', 'DanCap'),
(74, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp'),
(75, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp'),
(76, 'JBL Tune 510BT', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 1299, 900, 'uploads/JBL Tune 510BT.jpg', '<br />\r\n<b>Warning</b>:  Undefined variable $usuario in <b>C:xampphtdocsPrimeraParteProyAudifonosEmp');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `comentarios`
--

CREATE TABLE `comentarios` (
  `id` int(10) NOT NULL,
  `nombre` varchar(60) NOT NULL,
  `titulo` varchar(150) NOT NULL,
  `calificacion` int(10) NOT NULL,
  `comentario` varchar(3000) NOT NULL,
  `producto` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `comentarios`
--

INSERT INTO `comentarios` (`id`, `nombre`, `titulo`, `calificacion`, `comentario`, `producto`) VALUES
(1, 'Daniel', 'Excelente calidad, pero excesivo precio', 4, 'El sonido de los apple airpods MAX es inigualable, se nota la mano de apple, sin embargo el precio es demasiado elevado para unos audifonos, a menos de que seas amante de apple compralos, sino busca una opcion mas economica hasta de la misma marca', 'Apple Airpods MAX'),
(2, 'Sofia', 'Mala calidad no compren esos audifonos', 2, 'Me sorprende que mis audifonos no hayan durado ni 3 meses, con lo que cuesten fue una estafa, aun estoy viendo lo de la garantia, no se si fue mala suerte mia o realmente son malos audifonos', 'Apple Airpods MAX'),
(3, 'Chuy', 'Excelente calidad, precio-producto', 5, 'El audio es impresionante, hasta parece audio espacial, ademas del precio mega accesible, los rec', 'JBL Tune 510BT'),
(4, 'Jose', 'Mala calidad no compren esos audifonos', 4, 'no lo compren', 'Apple Airpods MAX'),
(5, 'Daniel', 'Mala calidad no compren esos audifonos', 4, 'Incluye cargador y USB marca 1Hora de alta calidad y caja blanca genérica más un cargador inalámbrico genérico (los accesorios no cuentan con garantía). Equipo reacondicionado: Dispositivo que anteriormente tuvo su debido uso y presentó fallas, por lo que requirió ser inspeccionado y restaurado por la misma marca reemplazando las piezas afectadas para que de nuevo sea funcional para su posterior venta. Cuenta con excelentes condiciones físicas, parecen nuevos y tienen plásticos; la caja está sellada.', 'JBL Tune 510BT');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `productos`
--

CREATE TABLE `productos` (
  `id` int(10) NOT NULL,
  `nombre` varchar(40) NOT NULL,
  `categoria` varchar(20) NOT NULL,
  `marca` varchar(30) NOT NULL,
  `descripcion` varchar(1500) NOT NULL,
  `cantidad` int(10) NOT NULL,
  `precio` int(10) NOT NULL,
  `conectividad` varchar(20) NOT NULL,
  `color` varchar(20) NOT NULL,
  `descuento` varchar(10) NOT NULL,
  `montodesc` int(10) NOT NULL,
  `imagen` varchar(255) NOT NULL,
  `imagen2` varchar(255) NOT NULL,
  `imagen3` varchar(255) NOT NULL,
  `imagen4` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `productos`
--

INSERT INTO `productos` (`id`, `nombre`, `categoria`, `marca`, `descripcion`, `cantidad`, `precio`, `conectividad`, `color`, `descuento`, `montodesc`, `imagen`, `imagen2`, `imagen3`, `imagen4`) VALUES
(2, 'JBL Auriculares In-Ear', 'earbuds', 'JBL', 'Los auriculares JBL In-Ear ofrecen una experiencia auditiva envolvente en un diseño compacto y cómodo. Diseñados para ajustarse perfectamente en el canal auditivo, estos auriculares in-ear proporcionan un sonido claro y nítido con un énfasis en los bajos, que es característico de la calidad de audio que se espera de la marca JBL. Con su construcción ergonómica, ofrecen comodidad durante periodos prolongados de uso y son ideales para actividades en movimiento. Algunos modelos pueden incluir características adicionales, como controles integrados para gestionar la reproducción de música y llamadas, así como micrófonos incorporados para una comunicación manos libres.', 0, 1349, 'Inalambrica', 'Blancos', 'no', 0, 'uploads/JBL - Auriculares In-Ear True Wireless Vibe 200TWS.jpg', 'uploads/JBL - Auriculares In-Ear True Wireless Vibe 200TWS.1.jpg', 'uploads/JBL - Auriculares In-Ear True Wireless Vibe 200TWS.2.jpg', 'uploads/JBL - Auriculares In-Ear True Wireless Vibe 200TWS.3.jpg'),
(3, 'Sony MDR-ZX310-R', 'diadema', 'Sony', 'Los auriculares Sony MDR-ZX310-R ofrecen una experiencia auditiva envolvente con un diseño elegante y funcional. Este modelo supraaural proporciona una calidad de sonido equilibrada, con énfasis en los tonos bajos, lo que brinda una reproducción de audio rica y satisfactoria. Su diseño plegable y liviano los hace ideales para llevar en movimiento, facilitando su transporte y almacenamiento cuando no están en uso. Con almohadillas acolchadas en las orejeras, los MDR-ZX310-R garantizan comodidad durante sesiones auditivas prolongadas. Su diadema ajustable permite un ajuste personalizado para diferentes tamaños de cabeza. Estos auriculares son compatibles con una variedad de dispositivos, como teléfonos inteligentes, reproductores de música y computadoras portátiles, gracias a su conector estándar de 3.5 mm.', 50, 999, 'Cable', 'Rojos', 'no', 0, 'uploads/Sony MDR-ZX310-R Audífonos de Diadema Plegables con microfono.jpg', 'uploads/Sony MDR-ZX310-R Audífonos de Diadema Plegables con microfono.1.jpg', 'uploads/Sony MDR-ZX310-R Audífonos de Diadema Plegables con microfono.2.jpg', 'uploads/Sony MDR-ZX310-R Audífonos de Diadema Plegables con microfono.3.jpg'),
(4, 'JBL Tune 510BT', 'diadema', 'JBL', 'Los auriculares JBL Tune 510BT son una opción moderna y versátil para aquellos que buscan una experiencia auditiva inalámbrica. Con conectividad Bluetooth, estos auriculares ofrecen la libertad de moverse sin restricciones, conectándose fácilmente a dispositivos como teléfonos inteligentes, tabletas y computadoras. Su diseño supraaural proporciona una experiencia cómoda, con almohadillas suaves que se ajustan sobre las orejas y una diadema ajustable para adaptarse a diferentes tamaños de cabeza. Uno de los puntos destacados de los JBL Tune 510BT es su calidad de sonido equilibrada y potente. Ofrecen bajos profundos y claridad en las frecuencias medias y altas, proporcionando una reproducción de audio envolvente. Además, estos auriculares cuentan con controles integrados en la orejera, lo que permite gestionar la reproducción de música, ajustar el volumen y responder llamadas de forma conveniente.', 45, 1299, 'Inalambrica', 'Rosas', 'si', 399, 'uploads/JBL Tune 510BT.jpg', 'uploads/JBL Tune 510BT.1.jpg', 'uploads/JBL Tune 510BT.2.jpg', 'uploads/JBL Tune 510BT.3.jpg'),
(5, 'Sony WF-C500', 'earbuds', 'Sony', 'Los auriculares inalámbricos Sony WF-C500 ofrecen una experiencia auditiva compacta y conveniente en un diseño ergonómico y sin cables. Diseñados para proporcionar un ajuste seguro y cómodo en el oído, estos auriculares son ideales para aquellos que buscan movilidad y libertad durante sus actividades diarias. Con tecnología Bluetooth, los Sony WF-C500 se conectan fácilmente a dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esta conectividad inalámbrica permite una experiencia sin enredos y sin restricciones, lo que facilita el uso en movimiento. Estos auriculares ofrecen una calidad de sonido equilibrada, con énfasis en los detalles y una reproducción clara de las frecuencias. Además, cuentan con controles táctiles intuitivos en cada auricular, lo que facilita la gestión de la reproducción de música, la respuesta a llamadas y la navegación entre pistas de manera sencilla.', 80, 2499, 'Inalambrica', 'Negros', 'si', 299, 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.jpg', 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.1.jpg', 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.2.jpg', 'uploads/Sony WF-C500 - Auriculares inámbricos Bluetooth con micrófono y Resistencia al Agua IPX4, Color Negro.3.jpg'),
(6, 'Apple Airpods MAX', 'diadema', 'Apple', 'Los Apple AirPods Max son auriculares over-ear diseñados para proporcionar una experiencia de audio premium con la calidad de sonido característica de la marca. Estos auriculares inalámbricos ofrecen un diseño elegante y materiales de alta calidad, combinados con la tecnología avanzada de Apple. Con una construcción de acero inoxidable y almohadillas de espuma viscoelástica, los AirPods Max ofrecen comodidad y durabilidad. El diseño over-ear proporciona un ajuste envolvente que ayuda a bloquear el ruido ambiental, permitiendo a los usuarios sumergirse completamente en su música o contenido. La tecnología de cancelación activa de ruido (ANC) de Apple está integrada en los AirPods Max, lo que permite eliminar de manera efectiva los sonidos no deseados del entorno. Además, estos auriculares cuentan con sensores que detectan cuándo están colocados en la cabeza y pausan automáticamente la reproducción cuando se retiran. ', 120, 11999, 'Inalambrica', 'Plata', 'no', 0, 'uploads/Apple AirPods MAX - Color Plata.jpg', 'uploads/Apple AirPods MAX - Color Plata.1.jpg', 'uploads/Apple AirPods MAX - Color Plata.2.jpg', 'uploads/Apple AirPods MAX - Color Plata.3.jpg'),
(7, 'Huawei Freebuds 5i', 'earbuds', 'Huawei', 'Los Huawei FreeBuds 5i son auriculares inalámbricos que ofrecen una experiencia auditiva cómoda y conveniente. Diseñados por Huawei, estos auriculares proporcionan una conectividad sin cables para una experiencia de escucha inalámbrica. Estos auriculares cuentan con un diseño ergonómico que se adapta cómodamente al oído, proporcionando un ajuste seguro y cómodo durante períodos prolongados de uso. Además, su diseño compacto y liviano facilita su transporte y almacenamiento, convirtiéndolos en una opción práctica para el uso diario. La conectividad Bluetooth permite emparejar fácilmente los FreeBuds 4i con dispositivos compatibles, como teléfonos inteligentes, tabletas y otros dispositivos con capacidad Bluetooth. Esto ofrece la libertad de moverse sin restricciones, ya que no hay cables que limiten la movilidad del usuario.', 50, 1199, 'Inalambrica', 'Morados', 'no', 0, 'uploads/Huawei FreeBuds 5i.png', 'uploads/Huawei FreeBuds 5i.1.jpg', 'uploads/Huawei FreeBuds 5i.2.jpg', 'uploads/Huawei FreeBuds 5i.3.jpg'),
(8, 'Bose QuietComfort', 'diadema', 'Bose', 'La característica más destacada de estos auriculares es su capacidad para reducir significativamente el ruido ambiental. Esto es especialmente útil en entornos ruidosos, como aviones o espacios públicos, permitiendo a los usuarios sumergirse completamente en su música o contenido. Diseño cómodo: Los auriculares Bose suelen tener un diseño ergonómico y acolchado para ofrecer comodidad durante períodos de uso prolongado. Los materiales de alta calidad también contribuyen a la sensación premium. Calidad de sonido: Bose es conocido por proporcionar una calidad de sonido nítida y equilibrada', 90, 13999, 'Inalambrica', 'Crema', 'no', 0, 'uploads/Bose QuietComfort Ultra con Audio Espacial.jpg', 'uploads/Bose QuietComfort Ultra con Audio Espacial.1.jpg', 'uploads/Bose QuietComfort Ultra con Audio Espacial.2.jpg', 'uploads/Bose QuietComfort Ultra con Audio Espacial.3.jpg'),
(9, 'Sennheiser Cx', 'diadema', 'Sennheiser', 'Calidad de Sonido: Sennheiser es conocido por ofrecer una calidad de sonido de alta fidelidad. Los auriculares CX suelen proporcionar una reproducción precisa de graves, medios y agudos, brindando una experiencia auditiva equilibrada. Diseño Intrauditivo: Los auriculares CX son del tipo intrauditivo, lo que significa que se colocan directamente en el canal auditivo. Este diseño ayuda a aislar el sonido ambiental y mejora la calidad del audio al proporcionar un sellado más efectivo. Conectividad: Dependiendo del modelo, algunos auriculares CX pueden ser con cable (con conector de 3.5 mm) o inalámbricos, utilizando tecnologías como Bluetooth.', 30, 399, 'Cable', 'Negros', 'no', 0, 'uploads/Sennheiser Audífonos CX 80S.jpg', 'uploads/Sennheiser Audífonos CX 80S.1.jpg', 'uploads/Sennheiser Audífonos CX 80S.2.jpg', 'uploads/Sennheiser Audífonos CX 80S.3.jpg'),
(10, 'Sony WH-CH520', 'diadema', 'Sony', 'Los auriculares Sony WH-CH520 ofrecen una experiencia de audio inalámbrica de alta calidad con su diseño supraaural que descansa cómodamente sobre las orejas. Gracias a la conectividad Bluetooth, estos auriculares proporcionan la libertad de movimiento sin la molestia de cables. Con una batería de larga duración, permiten disfrutar de horas continuas de reproducción de música o llamadas telefónicas con manos libres. Equipados con controles integrados y micrófono, brindan facilidad de uso y una experiencia de usuario completa. Además, su diseño plegable los hace convenientes para almacenar y transportar. La calidad de sonido equilibrada, junto con las almohadillas acolchadas para mayor comodidad, hace que los Sony WH-CH520 sean una opción atractiva para aquellos que buscan un rendimiento de audio premium y una experiencia de uso sin complicaciones.', 70, 1599, 'Inalambrica', 'Negros', 'no', 0, 'uploads/Sony Audífonos inalámbricos on-Ear WH-CH520.jpg', 'uploads/Sony Audífonos inalámbricos on-Ear WH-CH520.1.jpg', 'uploads/Sony Audífonos inalámbricos on-Ear WH-CH520.2.jpg', 'uploads/Sony Audífonos inalámbricos on-Ear WH-CH520.3.jpg'),
(11, 'Apple Airpods Pro', 'earbuds', 'Apple', 'Los Apple AirPods Pro son auriculares inalámbricos de última generación que ofrecen una experiencia auditiva excepcional. Destacan por su tecnología de Cancelación Activa de Ruido (ANC), sumergiendo al usuario en un sonido envolvente al filtrar eficazmente los sonidos externos. Además, cuentan con el innovador Modo de Transparencia, permitiendo la entrada de sonidos ambientales cuando sea necesario. Su diseño intrauditivo proporciona un ajuste cómodo y personalizado, respaldado por diferentes tamaños de almohadillas. Estos auriculares incluyen características avanzadas, como audio espacial para una experiencia tridimensional, controles táctiles intuitivos, resistencia al agua y al sudor con certificación IPX4, y sensores que pausan la reproducción automáticamente al retirarlos. ', 0, 5499, 'Inalambrica', 'Blancos', 'no', 0, 'uploads/Apple AirPods Pro (Segunda generación).jpg', 'uploads/Apple AirPods Pro (Segunda generación).1.jpg', 'uploads/Apple AirPods Pro (Segunda generación).2.jpg', 'uploads/Apple AirPods Pro (Segunda generación).3.jpg'),
(12, 'Bose Noise', 'diadema', 'Bose', 'Los auriculares Bose Noise Cancelling Headphones ofrecen una experiencia auditiva excepcional gracias a su tecnología de cancelación de ruido líder en la industria. Diseñados para sumergir al usuario en un mundo de sonido de alta calidad, estos auriculares cuentan con características avanzadas para una experiencia premium. La cancelación de ruido adaptativa ajusta continuamente la intensidad de la cancelación de acuerdo con el entorno, brindando una inmersión total en la música, podcasts o llamadas. Con un diseño elegante y cómodo, los Bose Noise Cancelling Headphones son ideales para un uso prolongado. Los controles táctiles intuitivos permiten un manejo sencillo, mientras que la duración de la batería garantiza largas horas de disfrute sin interrupciones.', 39, 10099, 'Inalambrica', 'Plata', 'no', 0, 'uploads/Bose Noise Cancelling Headphones 700.jpg', 'uploads/Bose Noise Cancelling Headphones 700.1.jpg', 'uploads/Bose Noise Cancelling Headphones 700.2.jpg', 'uploads/Bose Noise Cancelling Headphones 700.3.png'),
(13, 'Huawei Freebuds SE', 'earbuds', 'Huawei', 'Los auriculares Huawei FreeBuds SE son una opción atractiva para aquellos que buscan una experiencia auditiva inalámbrica de calidad. Este modelo ofrece un diseño elegante y ergonómico que se adapta cómodamente al oído, proporcionando un ajuste seguro y estable. Con la tecnología de cancelación de ruido activa, los FreeBuds SE permiten sumergirse en la música o las llamadas sin distracciones externas. Estos auriculares inalámbricos de Huawei ofrecen un sonido claro y nítido, destacando los detalles de la música y brindando una experiencia envolvente. Su estuche de carga compacto permite una portabilidad conveniente y proporciona horas adicionales de reproducción. ', 90, 1499, 'Inalambrica', 'Verde aqua', 'no', 0, 'uploads/HUAWEI FreeBuds SE Auriculares.jpg', 'uploads/HUAWEI FreeBuds SE Auriculares.1.jpg', 'uploads/HUAWEI FreeBuds SE Auriculares.2.jpg', 'uploads/HUAWEI FreeBuds SE Auriculares.3.jpg'),
(14, 'Apple Airpods Carga', 'earbuds', 'Apple', 'Los Apple AirPods representan la vanguardia de la experiencia auditiva inalámbrica. Diseñados por Apple, estos auriculares inalámbricos se destacan por su calidad de sonido excepcional, comodidad y facilidad de uso. Gracias al chip H1 de Apple, los AirPods ofrecen una conexión inalámbrica rápida y estable con dispositivos Apple, permitiendo una experiencia de emparejamiento sencillo y transiciones fluidas entre dispositivos. Los AirPods cuentan con sensores táctiles que permiten controlar la reproducción de música, ajustar el volumen y activar Siri con gestos intuitivos. Además, la función de sensores de proximidad pausa automáticamente la reproducción cuando se retiran de los oídos y la reinicia cuando se vuelven a colocar.', 96, 2999, 'Inalambrica', 'Blancos', 'no', 0, 'uploads/Apple AirPods (Tercera generación) con Estuche de Carga MagSafe.jpg', 'uploads/Apple AirPods (Tercera generación) con Estuche de Carga MagSafe.1.jpg', 'uploads/Apple AirPods (Tercera generación) con Estuche de Carga MagSafe.2.jpg', 'uploads/Apple AirPods (Tercera generación) con Estuche de Carga MagSafe.3.jpg'),
(15, 'Sony WH1000XM4', 'diadema', 'Sony', 'Los auriculares Sony WH-1000XM4 son una obra maestra de la tecnología auditiva que combina un diseño elegante con un rendimiento excepcional. Reconocidos por su capacidad de cancelación de ruido líder en la industria, estos auriculares proporcionan una experiencia auditiva inmersiva al bloquear eficazmente los sonidos no deseados del entorno. Equipados con la tecnología de cancelación de ruido adaptativa, los WH-1000XM4 ajustan automáticamente la intensidad de la cancelación de ruido según el entorno, brindando una experiencia personalizada. La calidad de sonido es impresionante, con graves profundos y agudos claros que capturan cada detalle de la música.', 75, 1899, 'Inalambrica', 'Azul fuerte', 'no', 0, 'uploads/Sony WH1000XM4-L Audífonos de Diadema inalámbricos con Noise Cancelling-Azul.jpg', 'uploads/Sony WH1000XM4-L Audífonos de Diadema inalámbricos con Noise Cancelling-Azul.1.jpg', 'uploads/Sony WH1000XM4-L Audífonos de Diadema inalámbricos con Noise Cancelling-Azul.2.jpg', 'uploads/Sony WH1000XM4-L Audífonos de Diadema inalámbricos con Noise Cancelling-Azul.3.jpg'),
(16, 'Galaxy Buds 2 Pro', 'earbuds', 'Samsung', 'Los Samsung Galaxy Buds Pro 2 son auriculares inalámbricos que ofrecen una experiencia auditiva de alta calidad en un diseño compacto y ergonómico. Diseñados para adaptarse cómodamente al oído, estos auriculares son ligeros y vienen con almohadillas intercambiables para un ajuste personalizado. Destacan por proporcionar un sonido equilibrado con bajos profundos y agudos claros, brindando una experiencia auditiva inmersiva. Gracias a la conectividad Bluetooth, los Galaxy Buds se emparejan de manera rápida y sencilla con dispositivos compatibles, como teléfonos inteligentes y tabletas. Además, cuentan con controles táctiles intuitivos que permiten gestionar la reproducción de musica', 30, 2699, 'Inalambrica', 'Grafito', 'no', 0, 'uploads/SAMSUNG Galaxy Buds 2 Pro.jpg', 'uploads/SAMSUNG Galaxy Buds 2 Pro.1.jpg', 'uploads/SAMSUNG Galaxy Buds 2 Pro.2.jpg', 'uploads/SAMSUNG Galaxy Buds 2 Pro.3.jpg'),
(17, 'LINK BITS', 'diadema', 'Bits', '10 horas y carga USB: El auricular inteligente con cancelación de ruido puede proporcionar hasta 10 horas de tiempo de reproducción de música. Además, puede cargar estos auriculares inalámbricos a través del conveniente puerto tipo C, 5 minutos de carga son suficientes para obtener 1 horas de reproducción cuando la batería está baja. BLUETOOTH 5.0 y fácil de cambiar: Bluetooth 5.0 significa una transmisión más rápida y estable, menor consumo de energía y señales más estables. Puede admitir dos dispositivos Bluetooth al mismo tiempo. Por lo tanto, si estás viendo una película en tu iPad y entra una llamada a tu iPhone, los audífonos pausan el video y responden la llamada. Al finalizar la llamada, se reanuda la película. Diseño plegable&Cojín transpirable: diseño liviano, solo 209 g, la audifonos diadema se puede ajustable según el tama para mucho comodo. Además, las orejeras de proteína blanda con relleno de espuma viscoelástica se adaptan a sus oídos. Son muy adecuados para la oficina en casa, cursos online, viajes, música y televisión, etc.', 98, 1200, 'Inalambrica', 'Negros', 'si', 299, 'uploads/LINK BITS.jpg', 'uploads/LINK BITS.1.jpg', 'uploads/LINK BITS.2.jpg', 'uploads/LINK BITS.3.jpg'),
(18, 'Skullcandy Mod in Ear', 'earbuds', 'Skullcandy', 'Skull-iQ Smart Feature Technology: activa los controles manos libres u otros asistentes de voz como Alexa descargando la aplicación Skull-iQ. Sin cables, sin preocupaciones: hemos incluido la tecnología de localización Tile para que puedas encontrar cualquiera de los dos auriculares con facilidad si llegas a perder alguno de ellos. Solo descarga la app Tile y haz que los audífonos emitan un sonido. Diseñados para la aventura: con ganchos confortables y protección contra sudor y agua IP55 llévate los audífonos Push Active contigo a cualquier aventura o entrenamiento. 44 horas de carga: entre el estuche de carga y los audífonos, los Push Active te brindan 44 horas de reproducción. Entérate cuanta pila te queda cada vez que sacas los audífonos de su estuche.\r\n\r\n', 89, 1000, 'Cable', 'Negros', 'no', 0, 'uploads/SKULLCANDY Audifonos.jpg', 'uploads/SKULLCANDY Audifonos.1.jpg', 'uploads/SKULLCANDY Audifonos.2.jpg', 'uploads/SKULLCANDY Audifonos.3.jpg'),
(19, 'STF ', 'diadema', 'STF', 'CALIDAD PARA CUALQUIER ACTIVIDAD: Los audífonos Aurum On Ear de conexión inalámbrica, son una excelente opción para que escuches tu música con un sonido extraordinario de calidad inigualable. DISEÑO MODERNO Y CÓMODO: Su diseño moderno e innovador en tonos metálicos te permite combinar tus audífonos con cualquier outfit, además, con sus cómodas almohadillas ultrasuaves ¡no vas a querer quitártelos ni para dormir! BATERÍA DE AMPLIA DURACIÓN: su batería te da hasta 10 horas continuas para que disfrutes tu música, pero si te quedas sin carga, no te preocupes, ya que su función dual te permite conectarlo a un cable de 3.5 mm para que no pares de reproducir tus playlists del momento', 76, 999, 'Inalambrica', 'Plata', 'no', 0, 'uploads/STF Audífonos.jpg', 'uploads/STF Audífonos.1.jpg', 'uploads/STF Audífonos.2.jpg', 'uploads/STF Audífonos.3.jpg'),
(20, 'HTC', 'earbuds', 'HTC', 'Los audífonos HTC Inalámbricos con tecnología Bluetooth 5.3 representan una opción avanzada para disfrutar de una experiencia auditiva sin cables. Estos auriculares, diseñados en el formato de \"earbuds\" inalámbricos, garantizan una conectividad rápida y estable gracias a la versión 5.3 de Bluetooth. Su posible inclusión de cancelación de ruido contribuye a aislar al usuario de distracciones externas, mientras que los controles táctiles o físicos permiten gestionar funciones como cambiar de pista o ajustar el volumen con facilidad. Con un estuche de carga que no solo protege sino que también proporciona cargas adicionales, estos audífonos se destacan por su diseño ergonómico, ofreciendo comodidad durante sesiones auditivas prolongadas.', 100, 4999, 'Inalambrica', 'Negros', 'si', 100, 'uploads/HTC Audifonos.jpg', 'uploads/HTC Audifonos.1.jpg', 'uploads/HTC Audifonos.2.jpg', 'uploads/HTC Audifonos.3.jpg');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `ventas`
--

CREATE TABLE `ventas` (
  `id` int(10) NOT NULL,
  `cliente` varchar(60) NOT NULL,
  `total` int(10) NOT NULL,
  `productos` varchar(8000) NOT NULL,
  `cantidad` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `ventas`
--

INSERT INTO `ventas` (`id`, `cliente`, `total`, `productos`, `cantidad`) VALUES
(1, 'DanCap', 20994, 'Galaxy Buds 2 Pro, Galaxy Buds 2 Pro, Galaxy Buds 2 Pro, Apple Airpods Carga, Apple Airpods Carga, Apple Airpods Pro', 6),
(2, 'DanCap', 20094, 'Galaxy Buds 2 Pro, Galaxy Buds 2 Pro, Galaxy Buds 2 Pro, Apple Airpods Carga, Apple Airpods Carga, Apple Airpods Pro', 6),
(3, 'DanCap', 20094, 'Galaxy Buds 2 Pro, Galaxy Buds 2 Pro, Galaxy Buds 2 Pro, Apple Airpods Carga, Apple Airpods Carga, Apple Airpods Pro', 6),
(4, 'DanCap', 17395, 'Galaxy Buds 2 Pro, Galaxy Buds 2 Pro, Apple Airpods Carga, Apple Airpods Carga, Apple Airpods Pro', 5),
(5, 'DanCap', 10599, 'Bose Noise', 1);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `carrito`
--
ALTER TABLE `carrito`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `comentarios`
--
ALTER TABLE `comentarios`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `productos`
--
ALTER TABLE `productos`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `ventas`
--
ALTER TABLE `ventas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `carrito`
--
ALTER TABLE `carrito`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=77;

--
-- AUTO_INCREMENT de la tabla `comentarios`
--
ALTER TABLE `comentarios`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT de la tabla `productos`
--
ALTER TABLE `productos`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- AUTO_INCREMENT de la tabla `ventas`
--
ALTER TABLE `ventas`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
